### ISSUE TITLE
Cleanup: Change this to be a single validate function

### ISSUE THREAD

**Issue by ecumene** [Hiba-Mohamed/Reactjs-Nurses-Assignment-Sheet#22]
https://github.com/Hiba-Mohamed/Reactjs-Nurses-Assignment-Sheet/blob/00a9c9e6846e150eaa7e43f937ea01edf537d0a8/src/pages/manageStaff.tsx#L179C1-L179C1

 - [x] This validation function could be written like this

```js
                        validate: (value) => validateNurseName(value, ShiftId),
```

 - [x] This breaks your error handling, but I don't think you need to handle every case. Try and see what error messages it gives you by default
 
```js
 // Before:

{errors?.nurseName?.type === "required" && (
  <p className="text-peach">This field is required</p>
)}
{errors?.nurseName?.type === "maxLength" && (
  <p className="text-peach">Nurse's name cannot exceed 30 characters</p>
)}
{errors.nurseName && errors.nurseName.type === "isNotDuplicate" && (
  <p className="text-peach">{errors.nurseName.message}</p>
)}

// After
{errors.nurseName && <p className="text-peach">{errors.nurseName.message}</p>}
```

**Comment by Hiba-Mohamed** [comment]
The error message it gives me for duplicate is the same I specified in the validation function However, it does not give error messaged for required and max length
