### ISSUE TITLE
Persist your data with useLocalStorage

### ISSUE THREAD

**Issue by ecumene** [Hiba-Mohamed/Reactjs-Nurses-Assignment-Sheet#33]
https://usehooks.com/uselocalstorage

Remove the window references
 - [x] [Here](https://github.com/Hiba-Mohamed/Reactjs-Nurses-Assignment-Sheet/blob/ed409458bffa054fe907cb4d397487a4ba4f21de/src/pages/manageStaff.tsx#L87)
 - [x] [Here](https://github.com/Hiba-Mohamed/Reactjs-Nurses-Assignment-Sheet/blob/ed409458bffa054fe907cb4d397487a4ba4f21de/src/pages/searchResult.tsx#L28)
 - [x] [Here](https://github.com/Hiba-Mohamed/Reactjs-Nurses-Assignment-Sheet/blob/ed409458bffa054fe907cb4d397487a4ba4f21de/src/components/shiftListComponent.tsx#L68)

**Comment by Hiba-Mohamed** [comment]
Had to use useEffect hook to synchronize the prop value between child and parent
